import requests
import json
import pandas as pd
import yfinance as yf
from prophet import Prophet
import warnings
warnings.filterwarnings("ignore")

# ── Step 1: Generate fresh forecast results ────────────────────────────
# We run a quick forecast for all 5 stocks to get current numbers
print("Generating fresh forecasts for chatbot context...")

companies = {
    "AAPL": "Apple",
    "JPM":  "JPMorgan",
    "GS":   "Goldman Sachs",
    "V":    "Visa",
    "MA":   "Mastercard"
}

results = []
for ticker, name in companies.items():
    raw = yf.download(tickers=ticker, period="2y",
                      interval="1d", progress=False)
    raw.columns = raw.columns.get_level_values(0)
    df = raw[["Close"]].reset_index()
    df.columns = ["ds", "y"]
    df["ds"] = pd.to_datetime(df["ds"]).dt.tz_localize(None)

    model = Prophet(
        yearly_seasonality=True,
        weekly_seasonality=True,
        daily_seasonality=False,
        changepoint_prior_scale=0.05
    )
    model.fit(df)
    future = model.make_future_dataframe(periods=30)
    forecast = model.predict(future)

    current = df["y"].iloc[-1]
    predicted = forecast["yhat"].iloc[-1]
    pct = ((predicted - current) / current) * 100

    results.append({
        "company": name,
        "ticker": ticker,
        "current_price": round(current, 2),
        "predicted_price_30days": round(predicted, 2),
        "expected_change_pct": round(pct, 2)
    })

results_df = pd.DataFrame(results).sort_values(
    "expected_change_pct", ascending=False
)
print("Forecasts ready!")
print()

# ── Step 2: Build context string ──────────────────────────────────────
# This is the KEY difference from full RAG:
# We simply convert our results table to text and inject it into the prompt
# No embeddings, no vector database needed — the data is small enough
context = "Here are the current 30-day stock price forecasts:\n\n"
for _, row in results_df.iterrows():
    direction = "increase" if row["expected_change_pct"] > 0 else "decrease"
    context += (
        f"- {row['company']} ({row['ticker']}): "
        f"Current price ${row['current_price']}, "
        f"Predicted price in 30 days ${row['predicted_price_30days']}, "
        f"Expected to {direction} by {abs(row['expected_change_pct'])}%\n"
    )

# ── Step 3: Chat function ──────────────────────────────────────────────
def ask_stocksense(question):
    """Send question + forecast context to Phi-3 and get answer."""
    prompt = f"""You are StockSense, a financial forecasting assistant.
You have access to 30-day stock price forecasts generated by a Prophet 
time series model. Answer questions using ONLY the data provided.
Be concise — 2 to 3 sentences maximum.
Do NOT make investment recommendations or financial advice.

FORECAST DATA:
{context}

QUESTION: {question}

ANSWER:"""

    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": "phi3",
            "prompt": prompt,
            "stream": False
        }
    )
    return response.json()["response"].strip()

# ── Step 4: Interactive chatbot ────────────────────────────────────────
print("=" * 55)
print("StockSense Chatbot")
print("Powered by Prophet forecasts + Phi-3")
print("Type 'quit' to exit")
print("=" * 55)
print()

while True:
    question = input("You: ").strip()

    if question.lower() in ["quit", "exit", "bye"]:
        print("Stopping Phi-3...")
        requests.post("http://localhost:11434/api/generate",
                     json={"model": "phi3", "keep_alive": 0})
        print("Goodbye!")
        break

    if not question:
        continue

    print("\nStockSense: ", end="", flush=True)
    answer = ask_stocksense(question)
    print(answer)
    print()